name: sakura_epub
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community: 3.2.0
  isar_community_flutter_libs: 3.2.0
  screen_brightness: ^1.0.1
  epubx: ^4.0.0
  fluttertoast: ^8.2.5
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  html: ^0.15.4
  http: ^1.1.0
  flutter_html_reborn: ^3.0.0
  fading_edge_scrollview: ^4.1.1
  path_provider: ^2.1.3
  selectable: ^0.3.1
  get: ^4.7.2
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.0
  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
  



  fonts:
    #book fonts
    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf 
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf    

    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya.ttf
    - family: Amazon Ember
      fonts:
        - asset: assets/fonts/Amazon-Ember-Regular.ttf
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
    - family: Bitter Pro
      fonts:
        - asset: assets/fonts/BitterPro-Regular.ttf
    - family: Bookerly
      fonts:
        - asset: assets/fonts/Bookerly.ttf
    - family: Droid Sans
      fonts:
        - asset: assets/fonts/DroidSans.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Var.ttf
    - family: Gentium Book Plus
      fonts:
        - asset: assets/fonts/GentiumBookPlus-Regular.ttf
    - family: Halant
      fonts:
        - asset: assets/fonts/Halant-Regular.ttf
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: LinLibertine
      fonts:
        - asset: assets/fonts/LinLibertine-Regular.ttf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata-Var.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Var.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Var.ttf

